import Head from "next/head";
import { Suspense } from "react";

import style from "@/styles/Home.module.css";
import ArticleList from "@/feature/articles/ArticleList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<div className={style.main}>Loading...</div>}>
        <ArticleList />
      </Suspense>
    </>
  );
}
